# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"\\\n\x0bVoteRequest\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x12\n\nlog_length\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\">\n\x0cVoteResponse\x12\x14\n\x0cvote_granted\x18\x01 \x01(\x08\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\x05\"\x80\x01\n\nLogRequest\x12\x10\n\x08leaderId\x18\x01 \x01(\x05\x12\x13\n\x0b\x63urrentTerm\x18\x02 \x01(\x05\x12\x11\n\tprefixLen\x18\x03 \x01(\x05\x12\x12\n\nprefixTerm\x18\x04 \x01(\x05\x12\x14\n\x0cleaderCommit\x18\x05 \x01(\x05\x12\x0e\n\x06suffix\x18\x06 \x03(\t\"P\n\x0bLogResponse\x12\x0e\n\x06nodeId\x18\x01 \x01(\x05\x12\x13\n\x0b\x63urrentTerm\x18\x02 \x01(\x05\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x05\x12\x0f\n\x07Success\x18\x04 \x01(\x08\"\"\n\x0fServeClientArgs\x12\x0f\n\x07Request\x18\x01 \x01(\t\"C\n\x10ServeClientReply\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\t\x12\x10\n\x08LeaderID\x18\x02 \x01(\t\x12\x0f\n\x07Success\x18\x03 \x01(\x08\x32\xa4\x01\n\x0bRaftService\x12\x31\n\x12receiveVoteRequest\x12\x0c.VoteRequest\x1a\r.VoteResponse\x12\x32\n\x0bserveClient\x12\x10.ServeClientArgs\x1a\x11.ServeClientReply\x12.\n\x11receiveLogRequest\x12\x0b.LogRequest\x1a\x0c.LogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTEREQUEST']._serialized_start=14
  _globals['_VOTEREQUEST']._serialized_end=106
  _globals['_VOTERESPONSE']._serialized_start=108
  _globals['_VOTERESPONSE']._serialized_end=170
  _globals['_LOGREQUEST']._serialized_start=173
  _globals['_LOGREQUEST']._serialized_end=301
  _globals['_LOGRESPONSE']._serialized_start=303
  _globals['_LOGRESPONSE']._serialized_end=383
  _globals['_SERVECLIENTARGS']._serialized_start=385
  _globals['_SERVECLIENTARGS']._serialized_end=419
  _globals['_SERVECLIENTREPLY']._serialized_start=421
  _globals['_SERVECLIENTREPLY']._serialized_end=488
  _globals['_RAFTSERVICE']._serialized_start=491
  _globals['_RAFTSERVICE']._serialized_end=655
# @@protoc_insertion_point(module_scope)
